name: Auto

on:
  schedule:
    - cron: '7 1,5,10,14,17,22 * * *'
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#providing-inputs
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: 'auto'
        required: true
        default: true

jobs:
  ping_streamlit:
    # 使用最新的 Ubuntu 环境
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit App
        # 通过 curl 命令发送一个 HTTP HEAD 请求（-I 表示 HEAD，-sS 隐藏进度信息）
        run: |
          curl -IsS "https://python-argo-c4brhpxzz73hnydb48pv5h.streamlit.app/" -o /dev/null
